theme: jekyll-theme-cayman
title: Personal Profile of Zintis Vandelis (MBA / Presales Software Professional)
description: Mastering data and building attractive presentation elements (Excel, Power BI, Power Query, MS Office Javascript APIs, FP&A Software)
